### ISSUE TITLE
Adam (and some others) optimizers not working

### ISSUE THREAD

**Issue by bwintertkb** [microsoft/tensorflow-directml#286]
Hey guys, thanks for your time reading this. Basically, I've created a GANN with tensorflow-directml to run on my AMD GPU. All seems to be fine except when I try to use some specific optimizers. Namely, Adam which is the one I would like to use most, but the error is the same for the rest of the optimizers which don't work.

ADAM optimizer:

2021-06-16 23:30:02.076691: I tensorflow/stream_executor/platform/default/dso_loader.cc:99] Successfully opened dynamic library H:\NFT_AI_generator\venv\lib\site-packages\tensorflow_core\python/directml.adbd007a01a52364381a1c71ebb6fa1b2389c88d.dll
2021-06-16 23:30:02.499379: I tensorflow/core/common_runtime/dml/dml_device_cache.cc:249] DirectML device enumeration: found 1 compatible adapters.
2021-06-16 23:30:02.499695: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2021-06-16 23:30:02.887365: I tensorflow/core/common_runtime/dml/dml_device_cache.cc:185] DirectML: creating device on adapter 0 (AMD Radeon RX 6900 XT)
2021-06-16 23:30:03.183315: I tensorflow/stream_executor/platform/default/dso_loader.cc:99] Successfully opened dynamic library Kernel32.dll
WARNING:tensorflow:From H:\NFT_AI_generator\venv\lib\site-packages\tensorflow_core\python\ops\nn_impl.py:183: where (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
Traceback (most recent call last):
  File "H:\NFT_AI_generator\main.py", line 20, in <module>
    training.train(data, discriminator, generator, EPOCHES, BATCH_SIZE, optimiser='Adam', update=True)
  File "H:\NFT_AI_generator\src\GANN\training.py", line 43, in train
    discriminator_loss, generator_loss = training_step(generator_optimizer,discriminator_optimizer, generator, discriminator, batch, batch_size=batch_size, k=1)
  File "H:\NFT_AI_generator\src\GANN\training.py", line 25, in training_step
    discriminator.trainable_variables))  # Takes a list of gradient and variables pairs
  File "H:\NFT_AI_generator\venv\lib\site-packages\tensorflow_core\python\keras\optimizer_v2\optimizer_v2.py", line 439, in apply_gradients
    kwargs={"name": name})
  File "H:\NFT_AI_generator\venv\lib\site-packages\tensorflow_core\python\distribute\distribute_lib.py", line 1940, in merge_call
    return self._merge_call(merge_fn, args, kwargs)
  File "H:\NFT_AI_generator\venv\lib\site-packages\tensorflow_core\python\distribute\distribute_lib.py", line 1947, in _merge_call
    return merge_fn(self._strategy, *args, **kwargs)
  File "H:\NFT_AI_generator\venv\lib\site-packages\tensorflow_core\python\keras\optimizer_v2\optimizer_v2.py", line 483, in _distributed_apply
    var, apply_grad_to_update_var, args=(grad,), group=False))
  File "H:\NFT_AI_generator\venv\lib\site-packages\tensorflow_core\python\distribute\distribute_lib.py", line 1553, in update
    return self._update(var, fn, args, kwargs, group)
  File "H:\NFT_AI_generator\venv\lib\site-packages\tensorflow_core\python\distribute\distribute_lib.py", line 2165, in _update
    return self._update_non_slot(var, fn, (var,) + tuple(args), kwargs, group)
  File "H:\NFT_AI_generator\venv\lib\site-packages\tensorflow_core\python\distribute\distribute_lib.py", line 2171, in _update_non_slot
    result = fn(*args, **kwargs)
  File "H:\NFT_AI_generator\venv\lib\site-packages\tensorflow_core\python\keras\optimizer_v2\optimizer_v2.py", line 465, in apply_grad_to_update_var
    update_op = self._resource_apply_dense(grad, var, **apply_kwargs)
  File "H:\NFT_AI_generator\venv\lib\site-packages\tensorflow_core\python\keras\optimizer_v2\adam.py", line 207, in _resource_apply_dense
    use_locking=self._use_locking)
  File "H:\NFT_AI_generator\venv\lib\site-packages\tensorflow_core\python\training\gen_training_ops.py", line 1644, in resource_apply_adam
    _six.raise_from(_core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.NotFoundError: No registered 'ResourceApplyAdam' OpKernel for 'DML' devices compatible with node {{node ResourceApplyAdam}}
         (OpKernel was found, but attributes didn't match) Requested Attributes: T=DT_DOUBLE, use_locking=true, use_nesterov=false
        .  Registered:  device='CPU'; T in [DT_HALF]
  device='CPU'; T in [DT_BFLOAT16]
  device='CPU'; T in [DT_FLOAT]
  device='CPU'; T in [DT_DOUBLE]
  device='DML'; T in [DT_FLOAT]
  device='DML'; T in [DT_HALF]
 [Op:ResourceApplyAdam]

For FTRL:

2021-06-16 23:31:26.282677: I tensorflow/stream_executor/platform/default/dso_loader.cc:99] Successfully opened dynamic library H:\NFT_AI_generator\venv\lib\site-packages\tensorflow_core\python/directml.adbd007a01a52364381a1c71ebb6fa1b2389c88d.dll
2021-06-16 23:31:26.702632: I tensorflow/core/common_runtime/dml/dml_device_cache.cc:249] DirectML device enumeration: found 1 compatible adapters.
2021-06-16 23:31:26.703000: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2021-06-16 23:31:27.093813: I tensorflow/core/common_runtime/dml/dml_device_cache.cc:185] DirectML: creating device on adapter 0 (AMD Radeon RX 6900 XT)
2021-06-16 23:31:27.384261: I tensorflow/stream_executor/platform/default/dso_loader.cc:99] Successfully opened dynamic library Kernel32.dll
WARNING:tensorflow:From H:\NFT_AI_generator\venv\lib\site-packages\tensorflow_core\python\ops\nn_impl.py:183: where (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
Traceback (most recent call last):
  File "H:\NFT_AI_generator\main.py", line 20, in <module>
    training.train(data, discriminator, generator, EPOCHES, BATCH_SIZE, optimiser='Ftrl', update=True)
  File "H:\NFT_AI_generator\src\GANN\training.py", line 43, in train
    discriminator_loss, generator_loss = training_step(generator_optimizer,discriminator_optimizer, generator, discriminator, batch, batch_size=batch_size, k=1)
  File "H:\NFT_AI_generator\src\GANN\training.py", line 25, in training_step
    discriminator.trainable_variables))  # Takes a list of gradient and variables pairs
  File "H:\NFT_AI_generator\venv\lib\site-packages\tensorflow_core\python\keras\optimizer_v2\optimizer_v2.py", line 439, in apply_gradients
    kwargs={"name": name})
  File "H:\NFT_AI_generator\venv\lib\site-packages\tensorflow_core\python\distribute\distribute_lib.py", line 1940, in merge_call
    return self._merge_call(merge_fn, args, kwargs)
  File "H:\NFT_AI_generator\venv\lib\site-packages\tensorflow_core\python\distribute\distribute_lib.py", line 1947, in _merge_call
    return merge_fn(self._strategy, *args, **kwargs)
  File "H:\NFT_AI_generator\venv\lib\site-packages\tensorflow_core\python\keras\optimizer_v2\optimizer_v2.py", line 483, in _distributed_apply
    var, apply_grad_to_update_var, args=(grad,), group=False))
  File "H:\NFT_AI_generator\venv\lib\site-packages\tensorflow_core\python\distribute\distribute_lib.py", line 1553, in update
    return self._update(var, fn, args, kwargs, group)
  File "H:\NFT_AI_generator\venv\lib\site-packages\tensorflow_core\python\distribute\distribute_lib.py", line 2165, in _update
    return self._update_non_slot(var, fn, (var,) + tuple(args), kwargs, group)
  File "H:\NFT_AI_generator\venv\lib\site-packages\tensorflow_core\python\distribute\distribute_lib.py", line 2171, in _update_non_slot
    result = fn(*args, **kwargs)
  File "H:\NFT_AI_generator\venv\lib\site-packages\tensorflow_core\python\keras\optimizer_v2\optimizer_v2.py", line 465, in apply_grad_to_update_var
    update_op = self._resource_apply_dense(grad, var, **apply_kwargs)
  File "H:\NFT_AI_generator\venv\lib\site-packages\tensorflow_core\python\keras\optimizer_v2\ftrl.py", line 178, in _resource_apply_dense
    use_locking=self._use_locking)
  File "H:\NFT_AI_generator\venv\lib\site-packages\tensorflow_core\python\training\gen_training_ops.py", line 2079, in resource_apply_ftrl
    _six.raise_from(_core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.NotFoundError: No registered 'ResourceApplyFtrl' OpKernel for 'DML' devices compatible with node {{node ResourceApplyFtrl}}
        .  Registered:  device='CPU'; T in [DT_HALF]
  device='CPU'; T in [DT_BFLOAT16]
  device='CPU'; T in [DT_FLOAT]
  device='CPU'; T in [DT_DOUBLE]
 [Op:ResourceApplyFtrl]
Press any key to continue . . .

```
Host System
--------------------------------------------------------------------------------
Windows 10 Version  : Windows 10 Version 20H2 (OS Build 19042.1052)
Processor           : AMD Ryzen 9 3900X 12-Core Processor, 3793 Mhz, 12 Core(s), 24 Logical Processor(s)
Memory              : 32GB RAM
DirectX Version     : DirectX 12

Python Environment
--------------------------------------------------------------------------------
Python Version      : 3.7.0
TensorFlow-DirectML : 1.15.5

DirectX Device
--------------------------------------------------------------------------------
Description         : AMD RX 6900 XT
Manufacturer        : AMD
Chip Type           : AMD RX 6900 XT
Dedicated Memory    : 16000 MB
Driver Version      : 21.4.1
```

Let me know if you need any other info :) Thank you in advance for all of your help!

**Comment by PatriceVignola** [comment]
For Adam, the problem is that DML devices in TensorFlow don't support double (float64) data types at the moment. To leverage DML here, you can try changing the datatype of your model to float32 or float16.

As for Ftrl, we don't implement this optimizer for DML yet as we decided to prioritize optimizers most often found in popular models.

**Comment by bwintertkb** [comment]
Thank you very much for your quick reply! Works now and it's pretty dam quick haha!

**Comment by PatriceVignola** [comment]
We're glad to hear that!
